name: mobile_dev_graph_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-3.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets\fonts\Rubik\Rubik-Black.ttf
        - asset: assets\fonts\Rubik\Rubik-BlackItalic.ttf
        - asset: assets\fonts\Rubik\Rubik-Bold.ttf
        - asset: assets\fonts\Rubik\Rubik-BoldItalic.ttf
        - asset: assets\fonts\Rubik\Rubik-ExtraBold.ttf
        - asset: assets\fonts\Rubik\Rubik-ExtraBoldItalic.ttf
        - asset: assets\fonts\Rubik\Rubik-Italic.ttf
        - asset: assets\fonts\Rubik\Rubik-Light.ttf
        - asset: assets\fonts\Rubik\Rubik-LightItalic.ttf
        - asset: assets\fonts\Rubik\Rubik-Medium.ttf
        - asset: assets\fonts\Rubik\Rubik-MediumItalic.ttf
        - asset: assets\fonts\Rubik\Rubik-Regular.ttf
        - asset: assets\fonts\Rubik\Rubik-SemiBold.ttf
        - asset: assets\fonts\Rubik\Rubik-SemiBoldItalic.ttf

    - family: Inter
      fonts:
        - asset: assets\fonts\Inter\Inter-Black.ttf
        - asset: assets\fonts\Inter\Inter-Bold.ttf
        - asset: assets\fonts\Inter\Inter-ExtraBold.ttf
        - asset: assets\fonts\Inter\Inter-ExtraLight.ttf
        - asset: assets\fonts\Inter\Inter-Light.ttf
        - asset: assets\fonts\Inter\Inter-Medium.ttf
        - asset: assets\fonts\Inter\Inter-Regular.ttf
        - asset: assets\fonts\Inter\Inter-SemiBold.ttf
        - asset: assets\fonts\Inter\Inter-Thin.ttf
